app/registrar/urls.py
from django.conf.urls import url, include
from app.registrar.views import index_registrar,registrar_view,registro_list,registro_edit,registro_delete,RegistroList,RegistroCreate,RegistroUpdate,RegistroDelete,exito

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index_registrar,name='index'),
    url(r'^nuevo$', RegistroCreate.as_view(),name='crear_registro'),
    url(r'^listar$', login_required(RegistroList.as_view()),name='listar_registro'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(RegistroUpdate.as_view()),name='editar_registro'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(RegistroDelete.as_view()),name='eliminar_registro'),
    url(r'^exito', exito,name='exito'),
	#url(r'^eliminar/(?P<id_alumno>\d+)/$', registro_delete,name='eliminar_registro'),    

]

cursos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

urlpatterns = [
    url(r'^$',index,name='inicio'),
    url(r'^admin/', admin.site.urls),
    url(r'^cursos/', include('app.curso.urls',namespace='curso')),
    url(r'^registrar/', include('app.registrar.urls',namespace='registrar')),
    url(r'^usuario/', include('app.usuarios.urls',namespace='usuarios')),
    url(r'^accounts/login/',login,{'template_name':'usuario/index.html'},name='login'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
   

]

app/registrar/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Alumno(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos=models.CharField(max_length=70)
	edad=models.IntegerField()
	telefono=models.CharField(max_length=12)
	email=models.EmailField()
	computadora=models.CharField(max_length=12)

	def __unicode__(self):
		return '{}'.format(self.nombre)
		

app/registrar/forms.py
from django import forms

from app.registrar.models import Alumno

class RegistrarForm(forms.ModelForm):

	class Meta:
		model=Alumno

		fields=[
			'nombre',
			'apellidos',
			'edad',
			'telefono',
			'email',
			'computadora',
		]
		labels = {
			'nombre': 'Nombre',
			'apellidos': 'Apellidos',
			'edad': 'Edad',
			'telefono':'Telefono',
			'email':'Email',
			'computadora':'Computadora'
		}
		widgets = {
			'nombre':forms.TextInput(attrs={'class':'validate','type':'text'}),
			'apellidos':forms.TextInput(attrs={'class':'validate'}),
			'edad':forms.TextInput(attrs={'class':'validate'}),
			'telefono':forms.TextInput(attrs={'class':'validate'}),
			'email':forms.TextInput(attrs={'class':'validate',}),
			'computadora':forms.TextInput(attrs={'class':'validate'}),
		}

app/registrar/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
# Create your views here.

from django.core.urlresolvers import reverse_lazy
from app.registrar.forms import RegistrarForm
from app.registrar.models import Alumno


def index_registrar(request):
	return render(request, 'registrar/index.html')

def registrar_view(request):
	if request.method == 'POST':
		form=RegistrarForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('registrar:index')
	else:
		form=RegistrarForm()

	return render(request,'registrar/registro_form.html',{'form':form})

def registro_list(request):
	registro = Alumno.objects.all().order_by('id')
	contexto = {'registros':registro}
	return render(request, 'registrar/registros_list.html',contexto)

def registro_edit(request,id_alumno):
		registro=Alumno.objects.get(id=id_alumno)
		if request.method=='GET':
			form=RegistrarForm(instance=registro)
		else:
			form=RegistrarForm(request.POST,instance=registro)
			if form.is_valid():
				form.save()
			return redirect('registrar:listar_registro')
		return render(request,'registrar/registro_form.html',{'form':form})
def registro_delete(request,id_alumno):
	registro = Alumno.objects.get(id=id_alumno)
	if request.method=='POST':
		registro.delete()
		return redirect('registrar:listar_registro')
	return render(request,'registrar/registro_delete.html',{'registrar':registro})

class RegistroList(ListView):
	#registro=Alumno
	model=Alumno
	template_name='registrar/registros_list.html'	
class RegistroCreate(CreateView):
	"""docstring for RegistroCreate"""
	model=Alumno
	form_class= RegistrarForm
	template_name='registrar/registro_form.html'
	success_url=reverse_lazy('registrar:listar_registro')
class RegistroUpdate(UpdateView):
	model=Alumno
	form_class= RegistrarForm
	template_name='registrar/registro_form.html'
	success_url=reverse_lazy('registrar:listar_registro')

class RegistroDelete(DeleteView):
	model=Alumno
	template_name='registrar/registro_delete.html'
	success_url=reverse_lazy('registrar:listar_registro')
	
def exito(request):
	return render(request,'registrar/exito.html')

templates/registrar/exito.html
{%extends 'base/base.html'%}

{%block content%}
	<div class="container col s12 m12 z-depth-4 center" style="padding: 40px">

		<h1 class="red-text text-darken-2">Registro exitoso!!!</h1>
		<h3 class="indigo-text text-darken-1">Gracias por registrarte</h3>
		<p>Tu registro fue exitoso en unos dias te enviaremos un correo y/o mensaje de texto con mas informacion sobre los cursos, fechas de inicio, costos, horarios,etc.</p>
		<p>Los cursos seran impartidos en el Centro Comunitario de Aprendizaje de la localidad </p>
		<p>Si aun no has revisado los temas que tendran los cursos te invitamos a que los revises dando clic en el siguiente boton</p>
		<a class="waves-effect waves-light btn-large red darken-4"><i class="material-icons right">forward</i>Temario</a>

	</div>

	<br>
{%endblock%}

templates/registrar/index.html
{%extends 'base/base.html' %}
{%load staticfiles%}

{%block header%}
	<h3 class="center-align" > Se bienvenido a este maravilloso mundo</h3>
{%endblock%}


{% block parallax%}
<div class="slider">
    <ul class="slides">
      <li>
        <img src="{%static 'img/info.jpg'%}"> <!-- random image -->
        <div class="caption center-align">
          <h3>Informatica</h3>
          <h5 class="light grey-text text-lighten-3">Aprende y explora nuevas cosas sobre computacion</h5>
        </div>
      </li>
      <li>
        <img src="{%static 'img/internet2.jpg'%}"> <!-- random image -->
        <div class="caption center-align">
          <h3>Internetn</h3>
          <h5 class="light grey-text text-lighten-3">¿Como funciona el Internet? Te explicamos como y la mejor forma de aprovechar tu conexion a Internet</h5>
        </div>
      </li>
      <li>
        <img src="{%static 'img/ofice4.jpg'%}"> <!-- random image -->
        <div class="caption center-align">
          <h3>Se un Profesional</h3>
          <h5 class="light grey-text text-lighten-3">Aprende a crear documentos, presentaciones, hojas de calculo y como aprovechar al maximo tu correo electronico</h5>
        </div>
      </li>
      <li>
        <img src="{%static 'img/pro4.jpg'%}"> <!-- random image -->
        <div class="caption center-align">
          <h3>Aplicaciones</h3>
          <h5 class="light grey-text text-lighten-3">No solo utilizes las aplicaciones crea tu mismo las tuyas.</h5>
        </div>
      </li>
    </ul>
  </div>
{% endblock %}

{%block content%}
<div class="container">
	<div class="section">
		<div class="row">
		    <div class="col s12 m4">
		      <div class="card medium">
		        <div class="card-image">
		          <img src="{%static 'img/registro.png'%}">
		          <span class="card-title blue-text text-darken-1 white">Registro</span>
		        </div>
		        <div class="card-content">
		          <p>Registrate para obtener mas informacion de los cursos</p>
		        </div>
		        <div class="card-action">
		          <a class="blue-text" href="{%url 'registrar:crear_registro'%}">Registrar</a>
		        </div>
		      </div>
		    </div>

		    <div class="col s12 m4">
		      <div class="card medium">
		        <div class="card-image">
		          <img src="{%static 'img/temario.jpg'%}">
		          <span class="card-title blue-text text-darken-1 white">Temario</span>
		        </div>
		        <div class="card-content">
		          <p>Consulta los temas que se enseñaran y asombrendete con lo que estas a punto de aprender</p>
		        </div>
		        <div class="card-action">
		          <a class="blue-text" href="{%url 'curso:index'%}">Temas</a>
		        </div>
		      </div>
		    </div>
		 </div>
	</div>
</div>

{%endblock%}

templates/registrar/registro_delete.html
{%extends 'base/base.html' %}

{%block content%}

<div class="row">
    <form class="col s12" method="POST">
    	{%csrf_token%}
	    <div class="row">
	        <div class="input-field col s12">
	        	<h3>Desea eliminar el alumno? {{object.nombre}}</h3>
	        </div>
	    </div>
	    <button class="btn waves-effect waves-light" type="submit" name="action">Si, eliminar
    		<i class="material-icons right">send</i>
  		</button>
  		<a href="{%url 'registrar:listar_registro'%}">Cancelar</a>
    </form>
</div>


<!--
	<form method="POST">
		#{%csrf_token%}
		#{{form.as_p}}
		<button class="btn waves-effect waves-light" type="submit" name="action">Registrar
    		<i class="material-icons right">send</i>
  		</button>
	</form>-->
{%endblock%}

templates/registrar/registro_form.html
{%extends 'base/base.html' %}
{%load staticfiles%}

{%block header%}
	
{%endblock%}

{%block parallax%}
<div class="parallax-container z-depth-1" style="height: auto">
	<div class="section no-pad-bot" style="padding-bottom: 40px">
		<div class="container center row" style="margin-top: 80px;opacity: 0.85 ">
			<div class="white black-text center col s12 m12 l6 offset-l3">
				<div class="modal-content">
					<form class="col s12 " style="padding: 40px" method="post">

						<h3 class="center">Registro</h3>

								{% csrf_token %}
								
								<div class="row">
									<div class="input-field col s6">
											<i class="material-icons prefix">account_circle</i>
											<input id="nombre" type="text" class="validate"  name="nombre">
											<label for="nombre">Nombre</label>
									</div>
								
									
										<div class="input-field col s6">
											
											<input id="apellidos"  type="text" class="validate" name="apellidos">
											<label for="apellidos">Apellidos</label>
										</div>
									
								</div>
								<div class="row">
									
										<div class="input-field col s12">
											<i class="material-icons prefix">date_range</i>
											<input id="edad"  type="text" class="validate" name="edad">
											<label for="edad">Edad</label>
										</div>
									
								</div>
								<div class="row">
									
										<div class="input-field col s12">
											<i class="material-icons prefix">email</i>
											<input id="correo" type="email" class="validate"  name="email">
											<label for="correo">Correo</label>
										</div>
									
								</div>
								<div class="row">
									
										<div class="input-field col s12">
											<i class="material-icons prefix">phone</i>
											<input id="telefono" type="text" class="validate"   name="telefono">
											<label for="telefono">Telefono</label>
										</div>
									
								</div>
								<div class="row black-text">
									<div id="compu1" class="left">
										<p>
										<p>¿Cuenta con computadora?</p>
										<label>
									        <input type="checkbox" name="computadora" value="Si" />
									        <span>Si</span>
									     </label>
									     <br>
									     <label>
									        <input type="checkbox" name="computadora" value="No" />
									        <span>No</span>
									     </label>
										</p>
									</div>
									
									
									
								</div>
							
		
				    <button class="btn-large waves-effect waves-light blue darken-3 " type="submit" name="action">Registrar
			    		<i class="material-icons right">send</i>
			  		</button>
			  		</form>
				</div>
			</div>
		</div>
		
	</div>
	<div class="parallax">
		<img src="{%static 'img/ninos.jpeg'%}">
	</div>
</div>





<br>

<!--
	<form method="POST">
		#{%csrf_token%}
		#{{form.as_p}}
		<button class="btn waves-effect waves-light" type="submit" name="action">Registrar
    		<i class="material-icons right">send</i>
  		</button>
	</form>-->
{%endblock%}

{%block content%}
{%endblock%}

templates/registrar/registros_list.html
{%extends 'base/base.html'%}

{%block content%}

	<table class="centered">
		<thead>
			<tr>
				<td>#</td>
				<td>Nombre</td>
				<td>Apellidos</td>
				<td>Edad</td>
				<td>Telefono</td>
				<td>Email</td>
				<td>Computadora</td>
				<td>Opciones</td>
			</tr>
		</thead>
		<tbody>
			{%if object_list%}
			{%for registro in object_list%}
			<tr>
				<td>{{registro.id}}</td>
				<td>{{registro.nombre}}</td>
				<td>{{registro.apellidos}}</td>
				<td>{{registro.edad}}</td>
				<td>{{registro.telefono}}</td>
				<td>{{registro.email}}</td>
				<td>{{registro.computadora}}</td>
				<td><a class="waves-effect waves-light indigo darken-3 btn" href="{% url 'registrar:editar_registro' registro.id%}">Editar</a>
					<a class="waves-effect waves-light red darken-3 btn" href="{% url 'registrar:eliminar_registro' registro.id%}">Eliminar</a>
				</td>
				</tr>

			{%endfor%}
			{%else%}
				<h1>No hay registros</h1>
			{%endif%}
		</tbody>
	</table>
{%endblock%}